### ISSUE TITLE
Definition\Snowflake - basetypes

### ISSUE THREAD

**Issue by ErikZigo** [keboola/php-datatypes#11]
Podle me je spatne definovana metoda `Definition\Snowflake::getBasetype()`

Pro celociselny datovy typy vraci jako basetype `INTEGER`
https://github.com/keboola/php-datatypes/blob/master/src/Definition/Snowflake.php#L173

Pro cisla s desetinou carkou to vraci `NUMERIC`
https://github.com/keboola/php-datatypes/blob/master/src/Definition/Snowflake.php#L181

Oboji je podle me spatne, protoze Snowflake u `DESCRIBE TABLE` vraci pro oboji datovy typ `NUMBER`
https://docs.snowflake.net/manuals/sql-reference/data-types-numeric.html#decimal-numeric
https://docs.snowflake.net/manuals/sql-reference/data-types-numeric.html#int-integer-bigint-smallint-tinyint-byteint

**Comment by Halama** [comment]
base types je nějaká sada námi předdefinovaných typů na které se vše snažíme mapovat ne? takže si myslím že by to mělo být ok

**Comment by Halama** [comment]
Ale netuším jestli to je někde popsaný.

**Comment by pivnicek** [comment]
j, base types jsou nasi definovane

**Comment by ErikZigo** [comment]
Aha ja myslel ze jsou to ty co vraci DB :)
Tak to si napisu na to vlatni metodu. Chtel bych to pouzit pri validaci struktury mapping db writeru vs existujici tabulka v DB

**Comment by pivnicek** [comment]
Aha, no, to je hlavne pro mapping od jinej source do jinej destination, jako nejnižší společný jmenovatel

**Comment by pivnicek** [comment]
Tak zaviram
