### ISSUE TITLE
Definition length - pretypovani

### ISSUE THREAD

**Issue by ErikZigo** [keboola/php-datatypes#15]
Tady by melo byt asi pretypovani na string, pokud hodnota neni null.

https://github.com/keboola/php-datatypes/blob/master/src/Definition/Common.php#L37

**Comment by ErikZigo** [comment]
To samy pro default value

https://github.com/keboola/php-datatypes/blob/master/src/Definition/Common.php#L43

**Comment by ErikZigo** [comment]
@pivnicek Je potreba v metadatech zachovavat datovy typ u default? Ty tady testujes integer:

https://github.com/keboola/php-datatypes/blob/f16967a5da1b67e4a9fb38b07a1b0df3e588abb8/tests/GenericStorageDatatypeTest.php#L121

Pritom podle anotaci vsude v kodu by to spravne melo byt ze default je bud string nebo null

**Comment by pivnicek** [comment]
@ErikZigo dobra pointa! mas pravdu, ma to byt `string`

**Comment by ErikZigo** [comment]
@pivnicek takze muzu upravit ten test?
