### ISSUE TITLE
enum (mysql?) should be varchar base type

### ISSUE THREAD

**Issue by Halama** [keboola/php-datatypes#9]
Enum has base type `NUMERIC` instead of `VARCHAR/STRING`
![image](https://user-images.githubusercontent.com/903531/43544867-8e403098-95d4-11e8-8891-292575a71287.png)

**Comment by pivnicek** [comment]
right, but regardless the `enum` should not be mapping to `numeric` for the general storage case either.  `STRING` should be the base mapping for all unknowns.  (and it is :) but looks like it may be broken here)

**Comment by pivnicek** [comment]
omg https://github.com/keboola/php-datatypes/blob/master/src/Definition/GenericStorage.php#L108

**Comment by Halama** [comment]
yes https://keboola.slack.com/archives/C02J3DKH3/p1533154602000228?thread_ts=1533152021.000007&cid=C02J3DKH3 :)

**Comment by Halama** [comment]
this whole package and generic storage class is a bit weird

**Comment by pivnicek** [comment]
#10  will "fix" this, but there could be other issues.
